### ISSUE TITLE
Useless link in "What is Freedoom?" page

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom.github.io#14]
Under the "Levels" section, the paragraph states that level bugs are reported here: https://github.com/freedoom/freedoom/labels/levels but this is not true as most level issues aren't labelled like this a lot. The number of issues labelled with "levels" is insignificant, so remove that link or redirect it to https://github.com/freedoom/freedoom/issues

**Comment by chungy** [comment]
Did you mean the Help page?

Regardless, the issue tracker in Freedoom just needs better curating, rather than changing the page. I'll do that (thankfully we don't have that many open issues).
