### ISSUE TITLE
Add Brutal Doom's Hell on Earth Starter Pack to Other Projects

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom.github.io#19]
Sergeant_Mark_IV used a lot of Freedoom's maps to create the mapset, many of which are still recognisable, such as map25 and map11, which respectively take after Freedoom's map25 and map10.

http://www.moddb.com/mods/brutal-doom/downloads/brutal-doom-hell-on-earth-starter-pack

**Comment by chungy** [comment]
Uses assets of the proprietary _Doom_ games. I'd honestly rather not promote it here, sorry.
