### ISSUE TITLE
Update video?

### ISSUE THREAD

**Issue by Voros2** [freedoom/freedoom.github.io#21]
Currently it's an old video running an older version of Freedoom. Would something like [this](https://www.youtube.com/watch?v=Rc4zIP1S6-I) be considered eligible?

**Comment by chungy** [comment]
Yeah, I've thought about the age of the current embedded video. The one you linked to seems like a fine alternative.

**Comment by chungy** [comment]
Fixed in 8c61a6946a507aaef242cf416fe450f7cd6394bb

**Comment by Voros2** [comment]
Might be a good idea to change a few lines in the about document too, because I don't think it's a "well-known fan-made Doom mod". Simply writing "a Doom mod" instead would suffice.
