### ISSUE TITLE
webp images not supported by GNOME Software Center

### ISSUE THREAD

**Issue by Eonfge** [freedoom/freedoom.github.io#26]
This discussion has come prior to where we are now:
https://github.com/flathub/flathub/pull/1222

Not sure though what the desired solution is. Over at Flathub, the idea was to use png for the time being when dealing with the metainfo.xml file.

**Comment by chungy** [comment]
As far as I understand things (and I'm pretty far from an authority), distributors are expected to download source images and convert them to PNG for local file system, regardless of what the source file format was.

I was actually the one that requested the AppStream spec to be changed to allow WebP (https://github.com/ximion/appstream/issues/252), though I also had a bit of an expectation that new stable releases of distros would sort out logistical issue before it becomes a real issue. This might actually just be an issue for appstream-glib to implement.

**Comment by Eonfge** [comment]
I don't object to it being part of the standard, not at all. It's just that, since September, not all platforms have yet been able to implement the appropriate handlers. With FreeDoom, this is the first time I run into this, and the Flathub maintainers also didn't know about this limitation yet.

For the time being, I proposed an update to flathub using converted png images. as a work around in this situation. Perhaps in a few months, webP is supported and then I can use the upstream images directly.

**Comment by mc776** [comment]
It's been three years and WebP is still causing problems.

Can someone please just convert all of these into something decent?

**Comment by fragglet** [comment]
Fixed by #32.
