### ISSUE TITLE
Cyber Griffin - New Game using Freedoom Assets

### ISSUE THREAD

**Issue by metalx1000** [freedoom/freedoom.github.io#27]
I've been working the last month or so on a new game using the assets from FreeDoom.
It's still under development, but I personally think it's great so far (says the guy who made it).
It's Free and Open Source and Cross Platform, using the Godot Game Engine.
Controls can be a keyboard, game pad, or touchscreen.

Hope you guys check it out and let me know what you think.
https://filmsbykris.com/games/2021/cyber-griffin/website/

Game play:
https://odysee.com/@metalx1000:1/Cyber-Griffin_gameplay_2021.02.16:b

**Comment by mc776** [comment]
This was added a while ago so I'll close it.

(That said, I think we need to make that projects page just a *bit* more prominent...)
