### ISSUE TITLE
Need to re-do and re-organize the screenshots

### ISSUE THREAD

**Issue by mc776** [freedoom/freedoom.github.io#50]
I remember we took all these in a previous, ultimately aborted drive to get this release out, but then never updated them as that release date fell through and assets continued to get replaced.

Most noticeable are the health bonuses and the bullet weapons.

**Comment by selliott512** [comment]
This is true. The screenshots took some amount of effort, so I wasn't eager to revisit them when the release fell though, but you are correct. Fortunately the new monsters are accurate (I think). Also, fortunately the website is not tagged. It can be updated as we see fit.

**Comment by mc776** [comment]
When I get home I'll try to convert the GZ screenshots to jpegs and run jpegoptim on them. The thumbnails could receive similar treatment.

The Choco thumbnails *might* benefit from this too, but from my experience the main screenshots are for the most part as good as they'll get.

**Comment by mc776** [comment]
On a somewhat related note, the screenshot I just picked for the front page, which I thought was the best-looking one that could immediately make sense to a Doom player who knew what to look for, turns out to be *way* too dark for a page with a light theme and could use a replacement...

**Comment by mc776** [comment]
So [this](https://github.com/freedoom/freedoom/issues/1305) was a thing.

I think having to update that xml file (which I didn't even know existed until now) every single time is an administrative nightmare.

Is there any way to create a symlink or whatever so the same URL can point to a file that can be unilaterally updated on the website end to fix any errors?

**Comment by mc776** [comment]
A suggestion on how to do this going forward:

Let's allow anyone to submit any screenshot in any format they want (even if not all of them are actually posted).

Shrink them to something reasonable, but the game settings and proportions can be whatever the submitter normally (or abnormally) uses. Make them pngs or jpegs depending on what's most efficient for that particular case.

Make sure the *thumbnails* are all 320x240 jpegs. This may take some cropping.

Make the xml file link to the thumbnails so any change in format won't get accidentally left behind. Set all their descriptions to just "Freedoom screenshot".

Make file names `tn_p1_1.jpg`, `p1_1.jpg`, `tn_p1_2.jpg`, `p1_2.jpg`, ... `tn_fdm_3.jpg`, `fdm1_3.jpg`, `tn_fdm1_4.jpg`, `fdm1_4.jpg`, with no description except in the titles or something.

This should minimize any future hassles.

**Comment by selliott512** [comment]
@mc776 I like how you've solved the immediate problem.

As to the file names - I like it with one additional suggestion - they could be placed in a sub-directory, so `current/tn_p1_1.jpg`, `current/p1_1.jpg` ... The reason I'd like to do that is in the future I'd like to minimize the number of files tied up in the version "bump" branches. New screen shots would be placed in `next` directory as they were created. People would be encouraged browse that directory. Maybe we could even have a "next screenshots" page (I'm not sure if that's worth doing). At release time the directory gets renamed `next` -> `current`. If we want we could rename `current` -> `previous`, but we don't need to to. It's safely in git anyway.

**Comment by mc776** [comment]
I definitely agree with having a couple files that say "current" but I don't think the additional interface stuff is all that necessary - if we even keep them (as opposed to just letting people use git) just maybe rename and put old screenshots into a folder and link to that (or make a new page for them).

Since the filenames aren't descriptive anymore, captions/title text (how do you do these in asciidoc format?) might read something like

> Map01 taken by m in GZDoom, no mods

> Map29 taken by beelzebaby999 in GZDoom with Hideous Destructor

> E1M9 taken by Martha Stewart in Chocolate-Doom with Doom 4 Vanilla

> Map14 of Mars War taken by anonymous in DSDA-Doom with HorrorMovieRei's Gothic Skins for Doom

**Comment by mc776** [comment]
Proposal:

8 screenshots for each game, numbered 1-8.
The XML always points to `tn_p1_1.jpg`, `tn_p2_1.jpg`, `tn_p2_2.jpg` and `tn_dm_1.jpg`.

So we'd have 8 thumbnails that always have the exact same filename:

tn_p1_1.jpg tn_p1_2.jpg tn_p1_3.jpg tn_p1_4.jpg
tn_p1_5.jpg tn_p1_6.jpg tn_p1_7.jpg tn_p1_8.jpg

tn_p2_1.jpg tn_p2_2.jpg tn_p2_3.jpg tn_p2_4.jpg
tn_p2_5.jpg tn_p2_6.jpg tn_p2_7.jpg tn_p2_8.jpg

tn_dm_1.jpg tn_dm_2.jpg tn_dm_3.jpg tn_dm_4.jpg
tn_dm_5.jpg tn_dm_6.jpg tn_dm_7.jpg tn_dm_8.jpg

linking to 8 big pictures that may or may not always have the same extension:

p1_1.* p1_2.* p1_3.* p1_4.*
p1_5.* p1_6.* p1_7.* p1_8.*

p2_1.* p2_2.* p2_3.* p2_4.*
p2_5.* p2_6.* p2_7.* p2_8.*

dm_1.* dm_2.* dm_3.* dm_4.*
dm_5.* dm_6.* dm_7.* dm_8.*

And we'll worry about old stuff later (if we even bother to instead of just relying on the git repository).

Would this work?
