### ISSUE TITLE
(not an issue) Can i use your music with credit?

### ISSUE THREAD

**Issue by scd74186** [freedoom/freedoom.github.io#65]
This isn't an issue, but i have no idea how this whole github pull request thing works. I'm interested in using some of the songs in the soundtrack as part of a game, and they would play as part of a radio. It would probably be free dlc, that is included with the game and can still be downloaded if you don't own the game. The problem is, the game would cost money, hence being able to download it without owning the game (by game, im not referring to freedoom). Also, whenever the song changes in the game, there will be a little box that pops up and shows the name of the song, who made it (if its a freedoom song, then it would be the freedoom team), and there would be a radio shop where you can ask about and find where the music is from. Also, is it true the full freedoom soundtrack across the versions has more than 900 songs?

**Comment by chungy** [comment]
Yes, you can use Freedoom's music as you wish, just make sure to include the [license text](https://github.com/freedoom/freedoom/blob/master/COPYING.adoc) somewhere in your distribution.

**Comment by scd74186** [comment]
ok, so i include a licence text in the game that includes your licence text?

**Comment by chungy** [comment]
Yes, that's all there is to it. You'll probably end up with such a file for licenses of all other software/assets you use too :)
